version: 2
updates:
  # bundler's rubygem dependencies
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    groups:
      deps-minor-patch:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      dev-deps-minor-patch:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
    open-pull-requests-limit: 10
    assignees:
      - 'Texarkanine'
    commit-message:
      prefix: 'fix'
      include: 'scope'

  # GitHub Actions dependencies
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    groups:
      github-actions-minor-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    open-pull-requests-limit: 5
    assignees:
      - 'Texarkanine'
    commit-message:
      prefix: 'chore(deps-ci)'

